//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager_v2.DataBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfExecutin { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> TagId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public decimal Size { get; set; }
        public int FolderId { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> ApertureUnit { get; set; }
        public Nullable<decimal> ExposureTime { get; set; }
        public Nullable<decimal> FocalLenght { get; set; }
        public byte[] Photo1 { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
